version: "3.7"
services:

  # Only Generate static files and go away!
  nuxt:
    build: ./frontend/
    volumes:
      - ./frontend:/usr/src/nuxt-app:rw
    environment:
      - API_ENDPOINT=http://localhost:8000/api/graphql
    command: [sh, -c, "npm install && npm run generate"]
