version: "3.7"
services:

  backend:
    build: ./backend/
    volumes:
      # This mounts local ./backend for applying changes in Wagtail!
      - ./backend:/app
    ports:
      - "7999:7999"
    command: ["./docker-entrypoint.sh"]
    # network_mode: "host" # vite proxy fails with error 500 without host network

  frontend:
    build: ./frontend/
    volumes:
      # This mounts local ./frontend for applying changes in NuxtJS!
      - ./frontend:/usr/src/nuxt-app
    ports:
      - "8000:8000"
      - "24678:24678"
    command: [sh, -c, "npm install && npm run dev"]
    environment:
      - API_URL="http://127.0.0.1:7999"
    depends_on:
      - backend
    # network_mode: "host" # vite proxy fails with error 500 without host network
