version: "3.7"
services:

  backend:
    build: ./backend/
    volumes:
      # This mounts local ./backend for applying changes in Wagtail!
      - ./backend:/app
    ports:
      - "7999:7999"
    command: ["./docker-entrypoint.sh"]

  frontend:
    build: ./frontend/
    volumes:
      # This mounts local ./frontend for applying changes in NuxtJS!
      - ./frontend:/usr/src/nuxt-app
    ports:
      - "8000:8000"
      - "24678:24678"
    command: [sh, -c, "npm install && npm run dev"]
    environment:
      - URL_BACKEND_SERVER=http://backend:7999
    depends_on:
      - backend
