version: "3.7"
services:

  backend:
    build: ./backend/
    volumes:
      # This mounts local ./backend for applying changes in Wagtail!
      - ./backend:/app
    ports:
      - "7999:7999"
    command: ["./docker-entrypoint.sh"]
    # network_mode: "host" # vite proxy fails with error 500 without host network
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis   
    depends_on:
      - postgres
      - redis
      - queue

  frontend:
    build: ./frontend/
    volumes:
      # This mounts local ./frontend for applying changes in NuxtJS!
      - ./frontend:/usr/src/nuxt-app
    ports:
      - "8000:8000"
      - "24678:24678"
    command: [sh, -c, "npm install && npm run dev"]
    environment:
      - API_URL="http://localhost:7999"
    depends_on:
      - backend
    # network_mode: "host" # vite proxy fails with error 500 without host network

  queue:
    build: ./backend/
    command: ["./docker-entrypoint-queue.sh"]
    environment:
      - MODE=dev
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=vas3k_club
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ./backend:/app:delegated
    depends_on:
      - postgres
      - redis

  # cron:
  #   build: ./backend/
  #   command: ["./docker-entrypoint-queue.sh"]
  #   container_name: club_cron
  #   depends_on:
  #     - club_app
  #     - postgres
  #     - redis
  #   ports: []

  postgres:
    image: postgres:11
    container_name: club_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vas3k_club
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"