version: "3.7"
services:

  # Only Generate static files and go away!
  nuxt:
    build: ./frontend/
    volumes:
      - ./frontend:/usr/src/nuxt-app:rw
    env_file:
    - ./backend/backend/.env
    command: [sh, -c, "npm install && npm run generate"]
